from enum import Enum

class Religion(Enum):
    CATHOLIC = "catholic"
    ORTHODOX = "orthodox"
    ISLAM = "islam"
    PAGANISM = "pagan"
    HERETIC = "heretic"
    SUNGOD = "sungod"

class FactionEnum(Enum):
    WALES = "wales"
    IRELAND = "ireland"
    NOVGOROD = "novgorod"
    TEUTONIC_ORDER = "teutonic_order"
    LITHUANIA = "lithuania"
    JERUSALEM = "jerusalem"
    ANTIOCH = "antioch"
    NORWAY = "norway"
    SCOTLAND = "scotland"
    MILAN = "milan"
    VENICE = "venice"
    SICILY = "sicily"
    SPAIN = "spain"
    DENMARK = "denmark"
    POLAND = "poland"
    HUNGARY = "hungary"
    RUSSIA = "russia"
    MONGOLS = "mongols"
    EGYPT = "egypt"
    FRANCE = "france"
    ENGLAND = "england"
    TURKS = "turks"
    MOORS = "moors"
    HOLY_ROMAN_EMPIRE = "hre"
    BYZANTIUM = "byzantium"
    PORTUGAL = "portugal"
    TIMURIDS = "timurids"
    AZTECS = "aztecs"
    PAPAL_STATES = "papal_states"
    SLAVE = "slave"
    
class AIModel(Enum):
    BALANCED_SMITH = "balanced smith"
    
class Role(Enum):
    LEADER = "leader"
    HEIR = "heir"
    NEVERLEADER="never_a_leader"
    SLAVER="sub_faction "
        
class Gender(Enum):
    MALE = "male"
    FEMALE = "female"
     
class Building(Enum):
    pass

class CityBuilding(Building):
    CORE_VILLAGE_BUILDING_NO_WALLS = ""
    CORE_TOWN_BUILDING_PALLISADE = "core_building wooden_pallisade"
    CORE_LARGE_TOWN_BUILDING_WOODEN_WALL = "core_building wooden_wall"
    CORE_CITY_BUILDING_STONE_WALL = "core_building stone_wall"
    CORE_CITY_HALL_TOWN_HALL = "city_hall town_hall"
    CORE_CITY_HALL_COUNCIL_CHAMBERS = "city_hall council_chambers"
    CITY_BARRACKS_TOWN_WATCH = "barracks town_watch"
    CITY_BARRACKS_TOWN_GUARD = "barracks town_guard"
    CITY_BARRACKS_CITY_WATCH = "barracks city_watch"
    CITY_MARKET_CORN_EXCHANGE = "market corn_exchange"
    CITY_MARKET_MARKET = "market market"
    CITY_MARKET_FAIRGROUND = "market fairground"
    CITY_SMITH_LEATHER_TANNER = "smith leather_tanner"
    CITY_SMITH_BLACKSMITH = "smith blacksmith"
    CITY_ROADS = "hinterland_roads roads"
    CITY_ROADS_PAVED = "hinterland_roads paved_roads"
    CITY_FARM_LEVEL_1 = "hinterland_farms farms"
    CITY_FARM_LEVEL_2 = "hinterland_farms farms+1"
    
class CastleBuilding(Building):
    CORE_CASTLE_BUILDING_MOTTE = "core_castle_building motte_and_bailey"
    CORE_CASTLE_BUILDING_WOODEN_WALL = "core_castle_building wooden_castle"
    CORE_CASTLE_BUILDING_STONE_WALL = "core_castle_building castle"
    CASTLE_BARRACKS_MUSTERING_HALL = "castle_barracks mustering_hall"
    CASTLE_BARRACKS_GARRISON_QUARTERS = "castle_barracks garrison_quarters"
    CASTLE_MISSILES_BOWYER = "missiles bowyer"
    CASTLE_MISSILES_PRACTICE_RANGE = "missiles practice_range"
    CASTLE_MISSILES_ARCHERY_RANGE = "missiles archery_range"
    CASTLE_SIEGE_BALLISTA = "castle_siege c_ballista_range"
    CASTLE_SIEGE_CATAPULT = "castle_siege c_catapult_range"
    EQUESTRIAN_STABLES = "equestrian stables"
    EQUESTRIAN_KNIGHTS_STABLES = "equestrian knights_stables"
    CASTLE_SMITH_LEATHER_TANNER = "castle_smith c_leather_tanner"
    CASTLE_SMITH_BLACKSMITH = "castle_smith c_blacksmith"
    CASTLE_ROADS = "hinterland_castle_roads c_roads"
    CASTLE_FARM_LEVEL_1 = "hinterland_farms farms"
    CASTLE_FARM_LEVEL_2 = "hinterland_farms farms+1"
    
class AztecCityBuilding(Building):
    AZTEC_CORE_CITY_BUILDING_NO_WALLS = ""
    AZTEC_CORE_CITY_BUILDING_PALLISADE = "core_building wooden_pallisade"
    AZTEC_CORE_CITY_BUILDING_WOODEN_WALL = "core_building wooden_wall"
    AZTEC_CORE_CITY_BUILDING_STONE_WALL = "core_building stone_wall"
    AZTEC_CITY_PALACE = "meso_palace palace"
    AZTEC_CITY_PALACE_COMPLEX = "meso_palace palace_complex"
    AZTEC_CITY_PALACE_ACROPOLIS = "meso_palace acropolis"
    AZTEC_CITY_MARKET_CORN_EXCHANGE = "meso_market marketplace"
    AZTEC_CITY_MARKET_MARKET = "meso_market plaza"
    AZTEC_CITY_MARKET_FAIRGROUND = "meso_market great_plaza"
    AZTEC_PYRAMID = "temple_pagan pyramid"
    AZTEC_GREAT_PYRAMID = "temple_pagan great_pyramid"
    AZTEC_HIGH_TEMPLE_PYRAMID = "temple_pagan high_temple"
    AZTEC_CITY_ROADS = "hinterland_roads roads"
    AZTEC_FARM_LEVEL_1 = "hinterland_farms farms"
    AZTEC_FARM_LEVEL_2 = "hinterland_farms farms+1"
