CAPITAL_CANDIDATES = {
        "Dublin_Province",
        "Cork_Province",
        "Wick_Province",
        "Edinburgh_Province",
        "Cardiff_Province",
        "Nottingham_Province",
        "Bruges_Province",
        "Rennes_Province",
        "Paris_Province",
        "Santiago_Province",
        "Toledo_Province",
        "Sevilla_Province",
        "Granada_Province",
        "Barcelona_Province",
        "Marrakesh_Province",
        "Algiers_Province",
        "Tripoli_Province",
        "Toulouse_Province",
        "Genoa_Province",
        "Naples_Province",
        "Tunis_Province",
        "Florence_Province",
        "Venice_Province",
        "Bern_Province",
        "Oslo_Province",
        "Kalmar_Province",
        "Roskilde_Province",
        "Oldenburg_Province",
        "Frankfurt_Province",
        "Prague_Province",
        "Thessalonica_Province",
        "Budapest_Province",
        "Reval_Province",
        "Stettin_Province",
        "Konigsberg_Province",
        "Peremyshl_Province",
        "Corinth_Province",
        "Alexandria_Province",
        "Ascalon_Province",
        "Acre_Province",
        "Damascus_Province",
        "Baghdad_Province",
        "Antioch_Province",
        "Iconium_Province",
        "Vilnius_Province",
        "Novgorod_Province",
        "Minsk_Province",
        "Smyrna_Province",
        "Constantinople_Province",
        "Ragusa_Province",
        "Bran_Province",
        "Preslav_Province",
        "Ankara_Province",
        "Yerevan_Province",
        "Cherson_Province",
        "Samandar_Province",
        "Kiev_Province",
        "Moscow_Province",
    }

SPECIAL_PAPAL_REGIONS = {"Roman_Province"}

SPECIAL_AZTEC_REGIONS = {"Tenochtitlan_Province"}

SPECIAL_SLAVE_REGIONS = {
    "North_America", 
    "Arguin_Province", 
    "Timbuktu_Province", 
    "Jolof_Province", 
    "Fezzan",
    "Dongola_Province",
    "Mekka_Province"
    }

CAPITAL_CANDIDATES_CONNECTIONS = {
    "Dublin_Province" : {"Cork_Province", "Cardiff_Province"},
    "Cork_Province": {"Dublin_Province", "Cardiff_Province"},
    "Cardiff_Province": {"Dublin_Province", "Nottingham_Province"},
    "Wick_Province": {"Edinburgh_Province", "Dublin_Province"},
    "Edinburgh_Province": {"Dublin_Province", "Nottingham_Province"},
    "Cardiff_Province": {"Cork_Province", "Dublin_Province"},
    "Nottingham_Province": {"Cardiff_Province", "Bruges_Province"},
    "Bruges_Province": {"Nottingham_Province", "Paris_Province"},
    "Rennes_Province": {"Paris_Province", "Bruges_Province"},
    "Paris_Province": {"Bruges_Province", "Bern_Province"},
    "Santiago_Province": {"Toledo_Province", "Sevilla_Province"},
    "Toledo_Province": {"Santiago_Province", "Granada_Province"},
    "Sevilla_Province": {"Granada_Province", "Toledo_Province"},
    "Granada_Province": {"Sevilla_Province", "Algiers_Province"},
    "Barcelona_Province": {"Toledo_Province", "Toulouse_Province"},
    "Marrakesh_Province": {"Sevilla_Province", "Granada_Province"},
    "Algiers_Province": {"Tunis_Province", "Marrakesh_Province"},
    "Tripoli_Province": {"Tunis_Province", "Alexandria_Province"},
    "Toulouse_Province": {"Barcelona_Province", "Bern_Province"},
    "Genoa_Province": {"Florence_Province", "Bern_Province"},
    "Naples_Province": {"Florence_Province", "Tunis_Province"},
    "Tunis_Province": {"Algiers_Province", "Tripoli_Province"},
    "Florence_Province": {"Genoa_Province", "Naples_Province"},
    "Venice_Province": {"Florence_Province", "Ragusa_Province"},
    "Bern_Province": {"Genoa_Province", "Paris_Province"},
    "Oslo_Province": {"Roskilde_Province", "Kalmar_Province"},
    "Kalmar_Province": {"Roskilde_Province", "Stettin_Province"},
    "Roskilde_Province": {"Oldenburg_Province", "Stettin_Province"},
    "Oldenburg_Province": {"Frankfurt_Province", "Stettin_Province"},
    "Frankfurt_Province": {"Oldenburg_Province", "Prague_Province"},
    "Prague_Province": {"Frankfurt_Province", "Budapest_Province"},
    "Thessalonica_Province": {"Preslav_Province", "Corinth_Province"},
    "Budapest_Province": {"Bran_Province", "Prague_Province"},
    "Reval_Province": {"Novgorod_Province", "Kalmar_Province"},
    "Stettin_Province": {"Roskilde_Province", "Konigsberg_Province"},
    "Konigsberg_Province": {"Vilnius_Province", "Peremyshl_Province"},
    "Peremyshl_Province": {"Konigsberg_Province", "Kiev_Province"},
    "Corinth_Province": {"Thessalonica_Province", "Tripoli_Province"},
    "Alexandria_Province": {"Ascalon_Province", "Tripoli_Province"},
    "Ascalon_Province": {"Alexandria_Province", "Acre_Province"},
    "Acre_Province": {"Ascalon_Province", "Damascus_Province"},
    "Damascus_Province": {"Acre_Province", "Antioch_Province"},
    "Baghdad_Province": {"Yerevan_Province", "Damascus_Province"},
    "Antioch_Province": {"Damascus_Province", "Damascus_Province"},
    "Iconium_Province": {"Ankara_Province", "Smyrna_Province"},
    "Vilnius_Province": {"Konigsberg_Province", "Minsk_Province"},
    "Novgorod_Province": {"Reval_Province", "Minsk_Province"},
    "Minsk_Province": {"Vilnius_Province", "Kiev_Province"},
    "Smyrna_Province": {"Iconium_Province", "Corinth_Province"},
    "Constantinople_Province": {"Preslav_Province", "Thessalonica_Province"},
    "Ragusa_Province": {"Venice_Province", "Thessalonica_Province"},
    "Bran_Province": {"Budapest_Province", "Preslav_Province"},
    "Preslav_Province": {"Bran_Province", "Constantinople_Province"},
    "Ankara_Province": {"Iconium_Province", "Smyrna_Province"},
    "Yerevan_Province": {"Baghdad_Province", "Samandar_Province"},
    "Cherson_Province": {"Kiev_Province", "Preslav_Province"},
    "Samandar_Province": {"Kiev_Province", "Yerevan_Province"},
    "Kiev_Province": {"Peremyshl_Province", "Cherson_Province"},
    "Moscow_Province": {"Novgorod_Province", "Minsk_Province"},
}