CAPITAL_CANDIDATES = {
        "Dublin_Province",
        "Cork_Province",
        "Wick_Province",
        "Edinburgh_Province",
        "Cardiff_Province",
        "Nottingham_Province",
        "Bruges_Province",
        "Rennes_Province",
        "Paris_Province",
        "Santiago_Province",
        "Toledo_Province",
        "Sevilla_Province",
        "Granada_Province",
        "Barcelona_Province",
        "Marrakesh_Province",
        "Algiers_Province",
        "Tripoli_Province",
        "Toulouse_Province",
        "Corinth_Province",
        "Genoa_Province",
        "Naples_Province",
        "Tunis_Province",
        "Florence_Province",
        "Venice_Province",
        "Bern_Province",
        "Oslo_Province",
        "Roskilde_Province",
        "Oldenburg_Province",
        "Frankfurt_Province",
        "Prague_Province",
        "Thessalonica_Province",
        "Budapest_Province",
        "Reval_Province",
        "Stettin_Province",
        "Konigsberg_Province",
        "Peremyshl_Province",
        "Corinth_Province",
        "Medina_Province",
        "Alexandria_Province",
        "Ascalon_Province",
        "Acre_Province",
        "Damascus_Province",
        "Baghdad_Province",
        "Antioch_Province",
        "Iconium_Province",
        "Vilnius_Province",
        "Novgorod_Province",
        "Minsk_Province",
        "Smyrna_Province",
        "Constantinople_Province",
        "Ragusa_Province",
        "Bran_Province",
        "Preslav_Province",
        "Ankara_Province",
        "Yerevan_Province",
        "Kutais_Province",
        "Cherson_Province",
        "Samandar_Province",
        "Kiev_Province",
        "Moscow_Province",
        "Volga-Bulgar_Province",
    }

SPECIAL_PAPAL_REGIONS = {"Roman_Province"}

SPECIAL_AZTEC_REGIONS = {"Tenochtitlan_Province"}

SPECIAL_SLAVE_REGIONS = {
    "North_America", 
    "Arguin_Province", 
    "Timbuktu_Province", 
    "Jolof_Province", 
    "Fezzan",
    "Dongola_Province",
    "Mekka_Province"
    }